/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account; sets HttpOnly session cookies */
        post: operations["registerWeb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; sets HttpOnly session cookies */
        post: operations["loginWeb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the cookie session */
        post: operations["refreshWeb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the cookie session */
        post: operations["logoutWeb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/native/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account; returns Bearer + rotating refresh tokens */
        post: operations["registerNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/native/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; returns Bearer + rotating refresh tokens */
        post: operations["loginNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/native/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a native refresh token (single use) */
        post: operations["refreshNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/native/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a native refresh session */
        post: operations["logoutNative"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/link-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an initial, add-institution, or update Link session */
        post: operations["createLinkToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/exchange-public-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist one linked Item (duplicates detected) and start its sync */
        post: operations["exchangePublicToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/hosted-link/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Poll a Hosted Link session until it finishes (web fallback) */
        post: operations["completeHostedLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All linked Items with accounts and sync health */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/connections/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect one institution and rebuild dependent analysis */
        delete: operations["disconnectItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plaid/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plaid server-to-server webhook (signature verified) */
        post: operations["plaidWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume saved manual answers */
        get: operations["getManualOnboarding"];
        /** Save manual answers; completes the manual gate only */
        put: operations["saveManualOnboarding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gates, phase, institution progress, and available actions */
        get: operations["getOnboardingStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/linking-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Declare account linking done; creates/advances the analysis run */
        post: operations["declareLinkingComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/financial-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest review snapshot: facts, coverage, actionable exceptions */
        get: operations["getFinancialReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/financial-review/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct or accept one review item (scoped, audited) */
        patch: operations["correctReviewItem"];
        trace?: never;
    };
    "/onboarding/financial-review/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rebuild facts and review after corrections */
        post: operations["recomputeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/financial-review/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the latest review; the only path to completion */
        post: operations["confirmReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed analysis phase or failed institution syncs */
        post: operations["retryAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or refresh one Expo push token */
        post: operations["registerPushToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push-tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one push token */
        delete: operations["revokePushToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: string;
            code?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerWeb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                    };
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    loginWeb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                    };
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    refreshWeb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                    };
                };
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    logoutWeb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                        accessToken: string;
                        refreshToken: string;
                        refreshExpiresInSeconds: number;
                    };
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    loginNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                        accessToken: string;
                        refreshToken: string;
                        refreshExpiresInSeconds: number;
                    };
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    refreshNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Session rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: {
                            id: string;
                            email: string;
                            onboardingComplete: boolean;
                        };
                        accessToken: string;
                        refreshToken: string;
                        refreshExpiresInSeconds: number;
                    };
                };
            };
            /** @description Invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    logoutNative: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createLinkToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    mode?: "add" | "update";
                    /** Format: uuid */
                    itemId?: string;
                };
            };
        };
        responses: {
            /** @description Link token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        linkToken: string;
                        expiration: string | null;
                        hostedLinkUrl: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Plaid error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    exchangePublicToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    publicToken: string;
                };
            };
        };
        responses: {
            /** @description Connection persisted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connection: {
                            id: string;
                            itemId: string;
                            institutionId: string | null;
                            institutionName: string | null;
                            status: string;
                            createdAt: string;
                            accounts: {
                                accountId: string;
                                name: string;
                                officialName: string | null;
                                mask: string | null;
                                type: string;
                                subtype: string | null;
                                currentBalance: number | null;
                                availableBalance: number | null;
                                isoCurrencyCode: string | null;
                            }[];
                            health?: {
                                /** @enum {string} */
                                syncStatus: "pending" | "syncing" | "complete" | "failed";
                                updateStatus: string;
                                oldestTransactionDate: string | null;
                                lastSyncedAt: string | null;
                                lastErrorCode: string | null;
                            } | null;
                            duplicate?: boolean;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Plaid error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    completeHostedLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    linkToken: string;
                };
            };
        };
        responses: {
            /** @description Session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "pending";
                    } | {
                        /** @constant */
                        status: "connected";
                        connection: {
                            id: string;
                            itemId: string;
                            institutionId: string | null;
                            institutionName: string | null;
                            status: string;
                            createdAt: string;
                            accounts: {
                                accountId: string;
                                name: string;
                                officialName: string | null;
                                mask: string | null;
                                type: string;
                                subtype: string | null;
                                currentBalance: number | null;
                                availableBalance: number | null;
                                isoCurrencyCode: string | null;
                            }[];
                            health?: {
                                /** @enum {string} */
                                syncStatus: "pending" | "syncing" | "complete" | "failed";
                                updateStatus: string;
                                oldestTransactionDate: string | null;
                                lastSyncedAt: string | null;
                                lastErrorCode: string | null;
                            } | null;
                            duplicate?: boolean;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connections: {
                            id: string;
                            itemId: string;
                            institutionId: string | null;
                            institutionName: string | null;
                            status: string;
                            createdAt: string;
                            accounts: {
                                accountId: string;
                                name: string;
                                officialName: string | null;
                                mask: string | null;
                                type: string;
                                subtype: string | null;
                                currentBalance: number | null;
                                availableBalance: number | null;
                                isoCurrencyCode: string | null;
                            }[];
                            health?: {
                                /** @enum {string} */
                                syncStatus: "pending" | "syncing" | "complete" | "failed";
                                updateStatus: string;
                                oldestTransactionDate: string | null;
                                lastSyncedAt: string | null;
                                lastErrorCode: string | null;
                            } | null;
                            duplicate?: boolean;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    disconnectItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        recomputeQueued: boolean;
                    };
                };
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    plaidWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        received: boolean;
                    };
                };
            };
            /** @description Verification failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    getManualOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved answers or null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        saved: {
                            payload: {
                                [key: string]: unknown;
                            };
                            updatedAt: string;
                        } | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    saveManualOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    fullName: string;
                    dateOfBirth: string;
                    /** @enum {string} */
                    maritalStatus: "single" | "married" | "domestic_partnership" | "divorced" | "widowed" | "prefer_not_to_say";
                    dependentsCount: number;
                    /** @enum {string} */
                    employmentStatus: "full_time" | "part_time" | "self_employed" | "unemployed" | "retired" | "student";
                    monthlyTakeHomeIncome: number;
                    monthlyHousingCosts: number;
                    monthlyFoodSpend: number;
                    monthlyTransportationCosts: number;
                    subscriptions: ("netflix" | "disney_hulu" | "amazon_prime" | "paramount" | "apple" | "xbox" | "playstation" | "nintendo" | "none")[];
                    monthlyEntertainmentSubscriptionsCosts?: number;
                    savingsAndEmergencyFunds: number;
                    totalDebt: number;
                    factorInDebtInterest: boolean;
                    financialGoals: ("emergency_fund" | "pay_off_debt" | "save_for_retirement" | "save_for_home" | "invest_more" | "reduce_spending")[];
                    additionalMoneyPools: ("vacation" | "miscellaneous" | "emergency" | "savings" | "investing")[];
                    /** @enum {string} */
                    riskComfort: "conservative" | "moderate" | "aggressive";
                    additionalContext: string;
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    getOnboardingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "phase": "waiting_for_history",
                     *       "gates": {
                     *         "hasLinkedInstitution": true,
                     *         "linkingDeclaredComplete": true,
                     *         "manualProfileComplete": true,
                     *         "analysisReviewable": false,
                     *         "financialReviewConfirmed": false
                     *       },
                     *       "analysis": {
                     *         "runId": "5b910c92-1890-4dce-8912-0e496d4091a4",
                     *         "status": "waiting_for_history",
                     *         "requestedLookbackDays": 180,
                     *         "institutions": {
                     *           "total": 2,
                     *           "ready": 1,
                     *           "limited": 0,
                     *           "failed": 0,
                     *           "pending": 1
                     *         },
                     *         "startedAt": "2026-08-24T20:00:00Z",
                     *         "reviewReadyAt": null,
                     *         "retryAllowed": false
                     *       },
                     *       "availableActions": [
                     *         "view_waiting",
                     *         "manage_connections",
                     *         "manage_notifications",
                     *         "logout"
                     *       ],
                     *       "onboardingComplete": false
                     *     }
                     */
                    "application/json": {
                        /** @enum {string} */
                        phase: "financial_linking" | "manual_profile_in_progress" | "waiting_for_history" | "classifying" | "review_ready" | "recomputing" | "failed_retryable" | "complete";
                        gates: {
                            hasLinkedInstitution: boolean;
                            linkingDeclaredComplete: boolean;
                            manualProfileComplete: boolean;
                            analysisReviewable: boolean;
                            financialReviewConfirmed: boolean;
                        };
                        analysis: {
                            runId: string;
                            /** @enum {string} */
                            status: "waiting_for_history" | "processing" | "review_ready" | "recomputing" | "confirmed" | "failed" | "superseded";
                            requestedLookbackDays: number;
                            institutions: {
                                total: number;
                                ready: number;
                                limited: number;
                                failed: number;
                                pending: number;
                            };
                            startedAt: string;
                            reviewReadyAt: string | null;
                            retryAllowed: boolean;
                        } | null;
                        availableActions: string[];
                        onboardingComplete: boolean;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    declareLinkingComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        phase: "financial_linking" | "manual_profile_in_progress" | "waiting_for_history" | "classifying" | "review_ready" | "recomputing" | "failed_retryable" | "complete";
                        gates: {
                            hasLinkedInstitution: boolean;
                            linkingDeclaredComplete: boolean;
                            manualProfileComplete: boolean;
                            analysisReviewable: boolean;
                            financialReviewConfirmed: boolean;
                        };
                        analysis: {
                            runId: string;
                            /** @enum {string} */
                            status: "waiting_for_history" | "processing" | "review_ready" | "recomputing" | "confirmed" | "failed" | "superseded";
                            requestedLookbackDays: number;
                            institutions: {
                                total: number;
                                ready: number;
                                limited: number;
                                failed: number;
                                pending: number;
                            };
                            startedAt: string;
                            reviewReadyAt: string | null;
                            retryAllowed: boolean;
                        } | null;
                        availableActions: string[];
                        onboardingComplete: boolean;
                    };
                };
            };
            /** @description No linked institution */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    getFinancialReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reviewId": "5fd0bb04-1826-4444-887d-95974853f623",
                     *       "analysisRunId": "5b910c92-1890-4dce-8912-0e496d4091a4",
                     *       "snapshotVersion": 3,
                     *       "status": "needs_confirmation",
                     *       "period": {
                     *         "requestedDays": 180,
                     *         "oldestObservedDate": "2026-03-04",
                     *         "throughDate": "2026-08-24"
                     *       },
                     *       "coverage": {
                     *         "band": "partial",
                     *         "reasons": [
                     *           {
                     *             "code": "UNLINKED_CARD_PAYMENT",
                     *             "message": "Payments to an unlinked card represent 18% of observed cash outflow."
                     *           }
                     *         ]
                     *       },
                     *       "coverageDetail": {},
                     *       "facts": {
                     *         "monthlyIncomeEstimate": 5200,
                     *         "averageMonthlyEconomicSpend": 3410,
                     *         "averageMonthlyCashObligations": 3890,
                     *         "availableToSpend": 7400
                     *       },
                     *       "fullFacts": {
                     *         "ruleVersion": "facts-v1",
                     *         "period": {
                     *           "oldestObservedDate": "2026-03-04",
                     *           "throughDate": "2026-08-24",
                     *           "observedDays": 174,
                     *           "normalizationMonths": 5.72
                     *         },
                     *         "income": {
                     *           "monthlyIncomeEstimate": 5200,
                     *           "estimateSource": "recurring_streams",
                     *           "totalObservedIncome": 29700,
                     *           "incomeStreams": []
                     *         },
                     *         "spend": {
                     *           "averageMonthlyEconomicSpend": 3410,
                     *           "grossEconomicSpend": 19800,
                     *           "refundsAndCredits": 290,
                     *           "netEconomicSpend": 19510,
                     *           "categoryTotals": []
                     *         },
                     *         "cashObligations": {
                     *           "averageMonthlyCashObligations": 3890,
                     *           "components": {
                     *             "netEconomicSpendMonthly": 3410,
                     *             "debtPaymentsMonthly": 0,
                     *             "externalCardPaymentsMonthly": 480
                     *           }
                     *         },
                     *         "balances": {
                     *           "totalAssets": 12400,
                     *           "totalLiabilities": 2100,
                     *           "netPosition": 10300,
                     *           "availableToSpend": 7400,
                     *           "accountCount": 4
                     *         },
                     *         "recurring": {
                     *           "outflows": []
                     *         },
                     *         "movement": {
                     *           "internalTransferTotal": 2500,
                     *           "linkedCardPaymentTotal": 4100,
                     *           "savingsTransferTotal": 1200,
                     *           "externalCardPaymentTotal": 2750
                     *         },
                     *         "unknowns": {
                     *           "unknownOutflowTotal": 420,
                     *           "unknownInflowTotal": 130,
                     *           "unknownShareOfOutflow": 0.02
                     *         }
                     *       },
                     *       "recurringStreams": [],
                     *       "incomeStreams": [],
                     *       "categoryTotals": [],
                     *       "reviewItems": [
                     *         {
                     *           "id": "7df09f9d-80f6-4a36-af60-66c768d57917",
                     *           "itemKey": "external_card_payment",
                     *           "type": "external_card_payment_unattributed",
                     *           "required": true,
                     *           "status": "open",
                     *           "evidence": {
                     *             "description": "AUTOPAY CARD PAYMENT",
                     *             "averageMonthlyAmount": 820
                     *           },
                     *           "proposedValue": null,
                     *           "confirmedValue": null,
                     *           "allowedActions": [
                     *             "connect_account",
                     *             "accept_coverage_limitation"
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        reviewId: string;
                        analysisRunId: string;
                        snapshotVersion: number;
                        /** @enum {string} */
                        status: "needs_confirmation" | "recomputing" | "confirmed";
                        period: {
                            requestedDays: number;
                            oldestObservedDate: string | null;
                            throughDate: string;
                        };
                        coverage: {
                            /** @enum {string} */
                            band: "complete" | "partial" | "insufficient";
                            reasons: {
                                code: string;
                                message: string;
                            }[];
                        };
                        coverageDetail: {
                            [key: string]: unknown;
                        };
                        facts: {
                            monthlyIncomeEstimate: number;
                            averageMonthlyEconomicSpend: number;
                            averageMonthlyCashObligations: number;
                            availableToSpend: number;
                        };
                        fullFacts: {
                            ruleVersion: string;
                            period: {
                                oldestObservedDate: string | null;
                                throughDate: string;
                                observedDays: number;
                                normalizationMonths: number;
                            };
                            income: {
                                monthlyIncomeEstimate: number;
                                /** @enum {string} */
                                estimateSource: "recurring_streams" | "observed_average" | "none";
                                totalObservedIncome: number;
                                incomeStreams: {
                                    streamKey: string;
                                    displayName: string;
                                    cadence: string;
                                    monthlyAmount: number;
                                    /** @enum {string} */
                                    confidence: "high" | "medium" | "low";
                                }[];
                            };
                            spend: {
                                averageMonthlyEconomicSpend: number;
                                grossEconomicSpend: number;
                                refundsAndCredits: number;
                                netEconomicSpend: number;
                                categoryTotals: {
                                    bucket: string;
                                    total: number;
                                    monthlyAverage: number;
                                    share: number;
                                    transactionCount: number;
                                }[];
                            };
                            cashObligations: {
                                averageMonthlyCashObligations: number;
                                components: {
                                    netEconomicSpendMonthly: number;
                                    debtPaymentsMonthly: number;
                                    externalCardPaymentsMonthly: number;
                                };
                            };
                            balances: {
                                totalAssets: number;
                                totalLiabilities: number;
                                netPosition: number;
                                availableToSpend: number;
                                accountCount: number;
                            };
                            recurring: {
                                outflows: {
                                    streamKey: string;
                                    displayName: string;
                                    cadence: string;
                                    averageAmount: number;
                                    monthlyAmount: number;
                                    amountVariance: number;
                                    /** @enum {string} */
                                    confidence: "high" | "medium" | "low";
                                    lastDate: string;
                                }[];
                            };
                            movement: {
                                internalTransferTotal: number;
                                linkedCardPaymentTotal: number;
                                savingsTransferTotal: number;
                                externalCardPaymentTotal: number;
                            };
                            unknowns: {
                                unknownOutflowTotal: number;
                                unknownInflowTotal: number;
                                unknownShareOfOutflow: number;
                            };
                        };
                        recurringStreams: {
                            streamKey: string;
                            displayName: string;
                            cadence: string;
                            averageAmount: number;
                            monthlyAmount: number;
                            amountVariance: number;
                            /** @enum {string} */
                            confidence: "high" | "medium" | "low";
                            lastDate: string;
                        }[];
                        incomeStreams: {
                            streamKey: string;
                            displayName: string;
                            cadence: string;
                            monthlyAmount: number;
                            /** @enum {string} */
                            confidence: "high" | "medium" | "low";
                        }[];
                        categoryTotals: {
                            bucket: string;
                            total: number;
                            monthlyAverage: number;
                            share: number;
                            transactionCount: number;
                        }[];
                        reviewItems: {
                            id: string;
                            itemKey: string;
                            type: string;
                            required: boolean;
                            /** @enum {string} */
                            status: "open" | "resolved" | "accepted" | "dismissed";
                            evidence: unknown;
                            proposedValue: unknown | null;
                            confirmedValue: unknown | null;
                            allowedActions: string[];
                        }[];
                    };
                };
            };
            /** @description ANALYSIS_NOT_REVIEWABLE — route to waiting and poll */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    correctReviewItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "accept_coverage_limitation" | "keep_manual_value" | "use_observed_value" | "set_value" | "confirm_stream" | "dismiss_stream" | "reclassify_transaction" | "reclassify_merchant";
                    snapshotVersion: number;
                    value?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "resolved" | "accepted";
                        recomputeQueued: boolean;
                    };
                };
            };
            /** @description REVIEW_ITEM_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description REVIEW_VERSION_STALE or RECOMPUTE_IN_PROGRESS */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description INVALID_CORRECTION_SCOPE */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    recomputeReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "queued" | "already_recomputing";
                    };
                };
            };
            /** @description ANALYSIS_NOT_REVIEWABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    confirmReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    snapshotVersion: number;
                };
            };
        };
        responses: {
            /** @description Confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        onboardingComplete: boolean;
                        alreadyConfirmed: boolean;
                    };
                };
            };
            /** @description REVIEW_VERSION_STALE or REVIEW_ITEMS_UNRESOLVED or ANALYSIS_NOT_REVIEWABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    retryAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued or already running */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "retry_queued" | "already_running";
                        code?: string;
                    };
                };
            };
            /** @description RETRY_NOT_AVAILABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    registerPushToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    /** @enum {string} */
                    platform: "ios" | "android" | "web";
                    deviceId?: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: {
                            id: string;
                            platform: string;
                            createdAt: string;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    revokePushToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description PUSH_TOKEN_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        code?: string;
                        details?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
}
